# Generated by Django 5.2 on 2025-05-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('services', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
