# Generated by Django 5.2 on 2025-05-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='services',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_code',
            field=models.CharField(default='+61', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='service',
            field=models.CharField(choices=[('home_loan', 'Home Loan'), ('personal_loan', 'Personal Loan'), ('car_loan', 'Car Loan'), ('insurance', 'Insurance'), ('other', 'Other')], default='+61', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
