# Generated by Django 5.2 on 2025-05-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_contact_phone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='boxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('abo', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_code',
            field=models.CharField(choices=[('+1', 'USA, Canada, and other countries'), ('+44', 'United Kingdom'), ('+91', 'India'), ('+61', 'Australia'), ('+81', 'Japan'), ('+33', 'France'), ('+49', 'Germany'), ('+39', 'Italy'), ('+55', 'Brazil'), ('+34', 'Spain'), ('+52', 'Mexico'), ('+7', 'Russia, Kazakhstan'), ('+86', 'China'), ('+27', 'South Africa'), ('+971', 'United Arab Emirates'), ('+66', 'Thailand'), ('+27', 'South Africa'), ('+61', 'Australia'), ('+20', 'Egypt'), ('+32', 'Belgium'), ('+31', 'Netherlands'), ('+34', 'Spain'), ('+45', 'Denmark'), ('+46', 'Sweden'), ('+48', 'Poland'), ('+49', 'Germany'), ('+53', 'Cuba'), ('+54', 'Argentina'), ('+60', 'Malaysia'), ('+63', 'Philippines'), ('+64', 'New Zealand'), ('+65', 'Singapore'), ('+81', 'Japan'), ('+82', 'South Korea'), ('+91', 'India'), ('+92', 'Pakistan'), ('+93', 'Afghanistan')], default='+91', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(choices=[('home_loan', 'Home Loan'), ('personal_loan', 'Personal Loan'), ('car_loan', 'Car Loan'), ('insurance', 'Insurance'), ('other', 'Other')], default='home_loan', max_length=100),
        ),
    ]
