# Generated by Django 5.2 on 2025-05-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_boxes_alter_contact_phone_code_alter_contact_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='img',
            field=models.ImageField(null=True, upload_to='box/'),
        ),
    ]
