from django.urls import path
from . import views
urlpatterns = [
     path('',views.homeView,name='home'),
     path('about/',views.aboutView, name='about'),
     path('services/',views.servicesView, name='servies'),
     path('calculator/',views.calculatorView,name='calculator'),
     path('contact/',views.Contact.as_view(),name='contact'),
     path('disclaimer/',views.DisclaimerView,name='disclaimer'),
     path('policy/',views.PolicyView,name='policy'),
     path('terms/',views.TermView,name='terms'),
     path('loan/cal/', views.calculate_emi , name='calculate'),
     path('extra/cal/', views.calculate_extra_emi , name='extra_calculate'),
     path('stamp/cal/', views.stamp_duty_calculator , name='stamp_calculate'),
     path('borrow/cal/', views.borrowing_calculator , name='borrow_calculate'),
     path('home/cal/', views.home_calculator , name='home_calculate'),
     path('lump/cal/', views.lump_calculator , name='lump_calculate'),
     path('mort/cal/', views.mort_calculator , name='mort_calculate'),
     path('save/cal/', views.saving_calculator , name='save_calculate'),
     path('save_goal/cal/', views.goal_calculator , name='goal_calculate'),
     path('compound/cal/', views.compound_calculator , name='compound_calculate'),
     path('rent/cal/', views.rent_calculator , name='rent_calculate'),
     path('income/cal/', views.income_calculator , name='income_calculate'),
     path('budget/cal/', views.budget_calculator , name='budget_calculate'),
     path('credit/cal/', views.credit_calculator , name='credit_calculate'),
     path('intro/cal/', views.intro_calculator , name='intro_calculate'),
     path('fortnight/cal/', views.fortnight_calculator , name='fortnight_calculate'),
]
